### ISSUE TITLE
LAN connection

### ISSUE THREAD

**Issue by compmonks** [peopleplusrobots/robo-op#2]

**Comment by zackjw** [comment]
Hi Pierre, we had the same problem at the university and, unofficially, had to find a creative solution.  Unofficially ;)

I’ve copied Madeline and Mike Jeffers here who are both still working at dFab and can tell you what protocol they’ve used since then.  It could involve a de facto ‘hacking’ of your system.  We called it “research”.

Best,
Zack

**Comment by madelinegannon** [comment]
Hi Pierre,

We just plugged our LAN connection into a wifi router and created a local network (an intranet, I guess).

**Comment by compmonks** [comment]
Hi Zack, thanks.
I was actually closing the issue because by doing a quick  "research" scanning of listening ports (currently 139) I could manage to establish a connection. The Getting started applet works fine but
commands does not seem to be read....

**Comment by compmonks** [comment]
ok, I finally got a working LAN version.
Even though you mentionned it, I had to explicit a few steps in order to reproduce the connection procedure with the students :

for the module:
#####################
! Working version for LAN connections
! Tips: - Robot IP can be checked in TeachPendant Menu
!                                     >System Info
!                                      >Controller Properties
!                                       >Network Connection
!                                        >LAN
!       - Make Sure the computer is in the same subnet (if the controller IP is 192.168.133.2, then the computer IP should be 192.168.133.20 for example)
!           - Go to your Network and Connection menu (in Windows: Network and Sharing Center)
!           - Click on the Local Area Connection you are using then 'Properties' > 'Internet Protocol Version 4' (TCP/Ipv4) > 'Properties'
!           - Select 'Use the following IP Adress' (Fixed IP) and type the corresponding IP (192.168.133.20 in this example)
!           - Do not forget to add as well the subnet mask and default gateway. Exactly the same than the Controller.
#####################

 for the Processing Applet file :
#####################
- WORKING VERSION FOR LAN CONNECTION
  - QUICK TIP : 
  - \- After loading the newly configured MOD file, in the TeachPendant menu, go to 'Production Window' > 'PP To Main' and then press the Play button
  - \- Make sure motors are 'ON' on the controller side and it is set to 'AUTOMATIC' mode  

#####################

All the best :)
Pierre

**Comment by madelinegannon** [comment]
Hi Pierre,

Thanks for posting your LAN configuration!

For safety reasons, we _strongly_ recommend running in MANUAL mode, not full Automatic.
Manual mode runs slower and someone will have to be hold down the deadman switch on the teach pendant. But unpredictable movements can happen when streaming commands, and manual mode can help minimize this risk.

We are looking forward to seeing what you make!

–Madeline
